name: research
channels:
  - defaults
  - conda-forge
  - glemaitre
  - akode
dependencies:
  - fairlearn
  - gym
  - imbalanced-learn
  - ipykernel
  - jupyter
  - jupyter_contrib_nbextensions
  - matplotlib
  - numpy
  - pandas
  # - pandas-profiling
  - pip
  - scikit-learn>=1.3
  - seaborn>=0.13.0
  # - setuptools>=40.6.3
  - tabulate
  - tempeh
  # - tqdm
  # - twine
  - xgboost
  - pip:
    - folktables
    # - tensorflow==1.14.0
    # - setuptools==40.6.3
    # - git+https://github.com/jackblandin/gym-tiger.git  # Use when not env is stable
    # - git+https://github.com/jackblandin/gym-dummy.git  # Use when not env is stable
    # - file:///Users/JBlandin/my/research/openai/custom_envs/gym-tiger  # use when editing locally
    # - file:///Users/JBlandin/my/research/openai/custom_envs/gym-dummy  # use when editing locally
    # PyPI - Doesn't work unless locally pip installed
    # - gym-dummy==0.0.2
